# Generated by Django 5.2.15 on 2026-06-12 19:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('dni', models.CharField(max_length=15, unique=True, verbose_name='DNI')),
                ('rol', models.CharField(choices=[('facilitador', 'Facilitador'), ('administrador', 'Administrador')], default='facilitador', max_length=20, verbose_name='Rol')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(choices=[('capital', 'Capital'), ('godoy_cruz', 'Godoy Cruz'), ('guaymallen', 'Guaymallén'), ('las_heras', 'Las Heras'), ('maipu', 'Maipú'), ('lujan', 'Luján de Cuyo'), ('san_martin', 'San Martín'), ('rivadavia', 'Rivadavia'), ('junin', 'Junín'), ('san_rafael', 'San Rafael'), ('general_alvear', 'General Alvear'), ('malargue', 'Malargüe'), ('lavalle', 'Lavalle'), ('san_carlos', 'San Carlos'), ('tupungato', 'Tupungato'), ('tunuyan', 'Tunuyán'), ('la_paz', 'La Paz'), ('santa_rosa', 'Santa Rosa'), ('general_san_martin', 'General San Martín'), ('otro', 'Otro')], max_length=50, verbose_name='Municipio')),
                ('episodio', models.CharField(choices=[('EP1', 'Episodio 1'), ('EP2', 'Episodio 2'), ('EP3', 'Episodio 3'), ('EP4', 'Episodio 4')], max_length=10, verbose_name='Episodio')),
                ('sede', models.CharField(help_text='Ej: CAU, Club Vecinal, Escuela N°123', max_length=100, verbose_name='Sede')),
                ('dias', models.CharField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo'), ('lunes_miercoles', 'Lunes y Miércoles'), ('martes_jueves', 'Martes y Jueves'), ('otro', 'Otro')], max_length=30, verbose_name='Días')),
                ('horario', models.CharField(blank=True, help_text='Ej: 9:00 a 13:00', max_length=50, verbose_name='Horario')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('facilitadores', models.ManyToManyField(blank=True, limit_choices_to={'rol': 'facilitador'}, related_name='cursos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Facilitadores')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['municipio', 'episodio', 'sede'],
                'unique_together': {('municipio', 'episodio', 'sede')},
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=15, unique=True, verbose_name='DNI')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('no_especifica', 'No especifica')], max_length=20, verbose_name='Género')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('escuela', models.CharField(blank=True, max_length=150, verbose_name='Escuela')),
                ('problemas_salud', models.TextField(blank=True, help_text='Alergias, condiciones médicas, etc.', verbose_name='Problemas de Salud')),
                ('tutor_nombre', models.CharField(blank=True, max_length=150, verbose_name='Nombre del Tutor')),
                ('tutor_dni', models.CharField(blank=True, max_length=15, verbose_name='DNI del Tutor')),
                ('tutor_contacto', models.CharField(blank=True, max_length=50, verbose_name='Contacto del Tutor')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar para dar de baja sin eliminar el historial', verbose_name='Activo')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de Baja')),
                ('motivo_baja', models.CharField(blank=True, help_text='Ej: OTRO, cambio de domicilio, etc.', max_length=200, verbose_name='Motivo de Baja')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='asistencia.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('ausente_justificado', 'Ausente Justificado')], max_length=25, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('facilitador', models.ForeignKey(limit_choices_to={'rol': 'facilitador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_marcadas', to=settings.AUTH_USER_MODEL, verbose_name='Facilitador')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias', to='asistencia.curso', verbose_name='Curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='asistencia.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha', 'estudiante__apellido'],
                'unique_together': {('estudiante', 'curso', 'fecha')},
            },
        ),
    ]
